genre_anime = {
    "Action":"Tokyo Revengers,Mars Red,Naruto Shippuden,Kaiji,Fullmetal Alchemist Brotherhood,Demon Slayer,Vinland Saga,One Punch Man,One Piece,Gintama,Jujutsu Kaisen,Psycho Pass,Akame Ga Kill,Black Lagoon,Sword Art Online,Mob Psycho 100,Cowboy Bebop,Berserk(Manga),Bleach,The God Of Highschool,Gurren Lagann,Fate Series,Jojo,Future Diary,Guilty Crown".split(","),
    "Comedy":"Gintama,Handa-kun,Fruits Basket,Shimoneta,Kaguya-sama:Love is War,Domestic Girlfriend,SK8 Infinity,Prison School,High School DxD,Kuroko no Basuke,Hajime no ippo,The Devil as a Part Timer,Konosuba,Grand Blue,Saiki K,One Piece,One Punch Man,".split(","),
    "Slice of Life":"Barakamon,Fruits Baskest,Joshiraku,Handa-kun,Classroom Of ELite,Orange,Nana,Anohana,Your Lie in April,Violet Evergarden,Wonder egg priority,Mushishi,".split(","),
    "Adventure":"To your eternity,Spice and Wolf,Inuyash,Seven Deadly Sins,One Piece,Jojo Bizare Adventure,Violet Evergarden,Made in Abyss,The Rising of the Shield hero,MushiShi,Naruto,Vinland Saga,Dororo,Fairy Tail".split(","),
    "Thriller":"Erased,Mars Red,Eden of The East,Shiki,Kajji,Darwin's Game,Parasyte,Black Butler,Kakegurui,Code Geass,Phantom,Classroom Of Elite,Black Butler,Paranoia Agent,Mushishi,Attack On titan,Death Note,Hyouka,Future Diary,Terror in Resonance,Mahou Shoujo Madoka,Steins Gate".split(","),
    "Fantasy":"Attack On Titan,Mushishi,Classroom of ELite,Edens Zero,Steins;Gate,SOA,Re-Zero,Goblin Slayer,Yasuke,Kakegurui,No Game No Life,Promised Neverland,Tokyo Ghoul,Hyouka,Violet Evergarden,Devilman Crybaby".split(","),
    "Shounen":"Gintama,One Punch Man,Rurouni Kenshin,Haikyuu,InuYasha,Fullmetal Alchemist,Seven Deadly Sins,Hunter X Hunter,Dragon Ball,Bleach,Magi,YU YU HAKUSHO,Naruto,Black Clover,Fairy Tail,Boku no hero academia,Demon Slayer,Food Wars,Major,Hajime no ippo,JoJo’s Bizarre Adventure".split(","),
    "Crime":"Monster,The Millionaire Detective Balance,Terror In Resonance,Hyouka,Beautiful Bones,Bungou Stray Dogs,Detective Conan,Gosick,Switch,Re:vale,Great Pretender,Psycho Pass,Un-Go,Ghost in the shell,Black Lagoon,Banana Fish,Death Note,The Beginning,Devil's Line".split(","),
    "Romance":"Honobono Log,Domestic Girlfriend,Nana,Oregairu,Bunny Girl senpai,Rent a girlfriend,Your Lie in April,Toradora,Domestic Girlfriend,Darling in the franx,Plastic Memories,Date a Live,Yuri on ice,Kaguya sama love is war,Your Name".split(","),
    "Sci-Fi":"Dr Stone,Cowboy Bebop,Darling in the Franxx,Made in abyss,Mahouka Koukou no Rettousei,Plastic Memories,Date a live,Gintama,Akira,Edens zero,86,Darwin's Game,Yasuke,Vivy,HAL,Hello world,Steins;Gate,Fullmetal Alchemist Brotherhood,Code Geass,Kill la Kill,Ergo Proxy,Gurren Lagann,Hello World,Ghost in the shell,Neon Genesis Evangelion,".split(","),
    "Anime Movies":"Ride Your wave,Wolf Children,A Silent Voice,Your Name,I want to eat your pancreas,Tenki no ko,Garden of words,Spirited away,Grave of Firefiles,HAL,Paparika,Perfect Blue,Hello World,5 cm per second,Akira,Whisker away,Howls Moving Castle,Ghost in the shell".split(","),
    "Horror":"Parasyte,Another,Dorohedro,Devilman Crybaby,Gantz,Hellsling,Blood C,Mononoke,Blood+,Highschool of Dead,Hell Girl,Ghost Hunt,Yami shibai,Kagewani,Black Butler,Witchblade,Boogiepop Phantom,Deadman Wonderland,Requiem from the Darkness,Vampire Knight,Dance in the vampire bund,Mononoke,Neo Ranga".split(',')
}